#!/bin/sh
[ -d "$HOME/.nofap" ] || mkdir -p $HOME/.nofap
[ -f "$HOME/.nofap/timestamp" ] || touch $HOME/.nofap/timestamp
[ -d "$HOME/.nofap/notes" ] || mkdir -p $HOME/.nofap/notes
timestamp_file="$HOME/.nofap/timestamp"
days="$(( ($(date +%s) - $(tail -n 1 $timestamp_file) ) / 86400))"
case "$(uname -s)" in
    *BSD*|*Darwin*)
        last_date="$(date -r $(tail -n 1 "$timestamp_file") +'%Y-%m-%d %H:%M')"
        first_date="$(date -r $(head -n 1 "$timestamp_file") +'%Y-%m-%d %H:%M')"
    ;;
    *)
        last_date="$(date -d @$(tail -n 1 "$timestamp_file") +'%Y-%m-%d %H:%M')"
        first_date="$(date -d @$(head -n 1 "$timestamp_file") +'%Y-%m-%d %H:%M')"
    ;;
esac

timestamp(){
    printf " ==> making the timestamp on $(date +%m/%d/%y)\n"
    printf "$(date +%s)\n" >> "$timestamp_file"
    printf " ==> timestamp succesfully created!\n"
}

day_name(){
    case "$(printf "$days" | tail -c 1)" in
        1) printf "day" ;;
        *) printf "days" ;;
    esac
}

reset_list(){
    printf " ==> last 5 resets:\n" 
    tail -n 5 "$timestamp_file" | while read line; do
        case "$(uname -s)" in
            *BSD*|*Darwin*) printf "     %s\n" "$(date -r "$line" +'%Y-%m-%d %H:%M')";;
            *) printf "     %s\n" "$(date -d "@$line" +'%Y-%m-%d %H:%M')";;
        esac
    done
}

note_write(){
    printf "$1\n" >> "$HOME/.nofap/notes/note$(date +%d-%m-%Y)"
}

note_read(){
    cat "$HOME/.nofap/notes/note${1}"
}

case "$1" in
    start*) timestamp ;;
    reset*) 
        printf " ==> Do you want to reset? [y/N] "
        read ANS
        case $ANS in
            [Yy]*) printf " ==> reseting...\n" 
                   timestamp
            ;;
            [Nn]*) exit 1 ;;
            *) exit 1 ;;
        esac
    ;;
    info*) 
        printf " ==> you didn't masturbated since $last_date ($days $(day_name))\n"
        reset_list
        [ -f "$HOME/.nofap/notes/note$(date +%d-%m-%Y)" ] || exit 1
        printf " ==> Current note:\n"
        note_read "$(date +%d-%m-%Y)" | sed 's/^/     /'
    ;;
    bar*) printf "$days\n" ;;
    note*)
        printf " ==> Making note on $(date +%d-%m-%Y)...\n"
        note_write "$2"
        printf " ==> Note created! To read it do 'nofap readnote $(date +%d-%m-%Y)'\n" 
    ;;
    readnote*) note_read "$2" ;;
esac
