#!/bin/sh
timestampfile="$HOME/.nofap/timestamp"
nofapdays="$(( ($(date +%s) - $(tail -n 1 $timestampfile) ) / 86400))"
nonunixts=$(date -d @$(tail -n 1 "$timestampfile") +'%Y-%m-%d %H:%M')
firstdate=$(date -d @$(head -n 1 "$timestampfile") +'%Y-%m-%d %H:%M')

pretext="         _      
  |\ | _ |__.._  
  | \|(_)|(_||_) 
             '   "

localreg(){
    case "$LANG" in
        ru*)
            msg_timestampon="метка времени поставлена на $(date +%m/%d/%y)..."
            msg_days="дн."
            msg_reset="вы сбросили таймер $(cat "$timestampfile" | wc -l) раз, начиная с $firstdate"
            msg_resets="последние сбросы:"
            msg_since="вы не мастурбировали начиная с $nonunixts ($nofapdays $msg_days)"
            state1="Первый день всегда тяжел, но вы сможете это сделать!"
            state2="День 1-3: Сильные позывы. Энергия и концентрация меняются"
            state3="День 4-7: Пик тяги. Повышенная мотивация и сексуальное напряжение"
            state4="2 Недели: Более стабильная энергия. Улучшена концентрация и уверенность в себе"
            state5="Месяцы спустя: Новый базовый уровень. Уверенность стала постоянной"
            state6="Годы спустя: Привычка вероятно больше не вернется"
            msg_current="Нынешнее состояние:"
            msg_sure="Вы уверены?"
            msg_reseting="сбрасываем таймер..."
            msg_errorbc="ой! произошла ошибка с временем! текущее время стоит до метки"
        ;;    
    *)
            msg_timestampon="making timestamp on $(date +%m/%d/%y)..."    
            msg_days="$(daysname)"
            msg_reset="you reseted $(cat "$timestampfile" | wc -l) times, starting from $firstdate"
            msg_resets="last resets:"
            msg_since="you didn't jerked off since $nonunixts ($nofapdays $msg_days)"
            state1="The first day often goes hard, but you can do it!"
            state2="Day 1-3: Strong urges. Energy and focus may start shifting"
            state3="Day 4-7: Peak cravings. Increased motivation and sexual tension"
            state4="Week 2: More stable energy. Improved focus and confidence"
            state5="Months later: a new baseline is established. Deep focus and stable energy are the norm"
            state6="Years later: the habit has a high chance of not returning"
            msg_current="Current state:"
            msg_sure="Are you sure?"
            msg_reseting="reseting..."
            msg_errorbc="oops! there's the error with your time! current time is before the timestamp"
        ;;
    esac
}

timestamp(){
        localreg
        printf " ==> $msg_timestampon\n"
        mkdir -p $HOME/.nofap
        echo "$(date +%s)" >> "$timestampfile"
}

daysname(){
    if [ "$(printf "$nofapdays" | tail -c 1)" = "1" ]; then
        printf "day"
    else
        printf "days"
    fi
}

resetshow(){
        localreg
        printf " == $msg_reset \n"
        printf " == $msg_resets \n"
        tail -n 5 "$timestampfile" | while read line; do
            printf "    %s\n" "$(date -d "@$line" +'%Y-%m-%d %H:%M')"
        done
}

currentstate(){
        localreg
        printf "\n == $msg_since\n"
        printf " == $msg_current \n    "
        if [ "$nofapdays" -lt 1 ]; then
            printf "$state1"
        elif [ "$nofapdays" -ge 1 ] && [ "$nofapdays" -le 3 ]; then
            printf "$state2"
        elif [ "$nofapdays" -ge 4 ] && [ "$nofapdays" -le 7 ]; then
            printf "$state3"
        elif [ "$nofapdays" -ge 7 ] && [ "$nofapdays" -le 17 ]; then
            printf "$state4"
        elif [ "$nofapdays" -ge 17 ] && [ "$nofapdays" -le 365 ]; then
            printf "$state5"
        elif [ "$nofapdays" -ge 365 ]; then
            printf "$state6"
        fi
}

case "$1" in
    start*) timestamp ;;
    reset*)
        localreg
        printf " $msg_sure [y/n] "
        read ANS
        case $ANS in
            [Yy]*) 
                printf " ==> $msg_reseting\n"
                timestamp
                printf " NOOOOOOOO FAP ENVIRONMENTING\n"
            ;;
            [Nn]*) exit 1 ;;
        esac
    ;;
    info*)
        localreg
        printf "%s $pretext\n"
        if [ "$(date +%s)" -lt "$(tail -n 1 "$timestampfile")" ]; then
            printf "$msg_errorbc"
            exit 1
        fi
        resetshow
        currentstate
    ;;
    bar*) printf "$nofapdays" ;;
    note*) echo "$2" | tee -a "$HOME/.nofap/note$(date +%Y%m%d)" ;;
    readnote|rn*) printf " == your note for today is:\n" && cat "$HOME/.nofap/note$(date +%Y%m%d)" ;;
esac

printf "\n"
